[Unit]
Requires=lc1c-egress@lc1c-edge.service lc1c-egress@lc1c-front.service lc1c-egress@lc1c-runtime.service
After=lc1c-egress@lc1c-edge.service lc1c-egress@lc1c-front.service lc1c-egress@lc1c-runtime.service
