export const frequencyLabels = { PERIODIC: 'Periódica', CONDITION_BASED: 'Por condición', COUNTER_BASED: 'Por contador', NO_FIXED_FREQUENCY: 'Sin frecuencia fija' }
export const statusLabels: Record<string, string> = { PLANNED: 'Programada', NOT_STARTED: 'Sin iniciar', IN_PROGRESS: 'En curso', PARTIAL: 'Parcial', COMPLETED: 'Completa', NOT_PERFORMED: 'No realizada', POSTPONED: 'Postergada', CANCELLED: 'Cancelada' }
export const cycleLabels: Record<string, string> = { CURRENT: 'Al día', UPCOMING: 'Próxima', OVERDUE: 'Vencida', NO_HISTORY: 'Sin historial', NO_COMPLETE: 'Sin ejecución completa', UNCERTAIN: 'Fecha por confirmar', NO_FREQUENCY: 'Sin frecuencia fija', PARTIAL_PENDING: 'Parcial pendiente' }
export const reasons = ['Falta de tiempo', 'Taller', 'Falta de repuesto', 'Proveedor externo', 'Recursos', 'Condición operativa', 'Reprogramación', 'Otro'] as const
export interface Scope { id?: string; description: string; quantity: number | string; unit: string; required: boolean; notes: string }
export interface RexTask { id: string; code: string; line: string; areaId: string; equipmentId: string | null; name: string; description: string; specialty: string; impact: string; criticality: string; active: boolean; frequencyType: keyof typeof frequencyLabels; intervalMonths: number | null; frequencyCriteria: string; referenceOt: string; technicalPlan: string; controlData: string; justification: string; interventionTime: string; resources: Record<string, string>; estimates: Estimate[]; scope: Scope[]; documents: { id?: string; name: string; path: string; type: string; notes: string }[] }
export interface RexEvent { id: string; name: string; type: string; startDate: string | null; endDate: string | null; exercise: number | null; status: string; notes: string }
export interface ExecutionItem extends Scope { id: string; completed: number | string; reason: string; status: string }
export interface RexExecution { id: string; taskId: string; eventId: string | null; intent: 'FULL_TASK' | 'PENDING_RESOLUTION'; status: string; startedAt: string | null; performedAt: string | null; ot: string; notes: string; responsibleId: string | null; createdAt: string; items: ExecutionItem[]; taskSnapshot: { name: string; areaCode: string; estimate?: Estimate | null; resources?: Record<string, string> }; resolutions: { pendingId: string; quantity: string | number }[] }
export interface RexPending { id: string; originItemId: string; quantity: string | number; remaining: string; reason: string; notes: string; originDate: string | null; taskId: string; executionId: string; component: string; unit: string; resolutions: { id: string; executionId: string; quantity: string | number; performedAt: string | null }[] }
export interface RexState { revision: number; config: EstimateConfig; tasks: RexTask[]; events: RexEvent[]; executions: RexExecution[]; pending: RexPending[]; areas: { id: string; code: string; name: string }[]; equipment: { id: string; area: string; name: string }[]; responsibles: { id: string; name: string; active: boolean }[] }
import type { Estimate, EstimateConfig } from './estimation'
