import { useMemo } from 'react'
import { AREA_FILTER_ALL, PLANT_AREAS, areaLabel } from '../../config/areas'
import { ALL_LEVELS, LEVEL_0, LEVEL_1, isLevelVisible } from '../../config/plantLevels'
import { getAssetMaintenanceMap } from '../../maintenance/domain/maintenanceSelectors'
import { MAINTENANCE_STATUSES, type MaintenanceStatus } from '../../maintenance/domain/maintenanceTypes'
import { useMaintenanceStore } from '../../maintenance/store/maintenanceStore'
import { useSceneStore } from '../../store/sceneStore'

const labels: Record<MaintenanceStatus, string> = { OVERDUE: 'Overdue', CRITICAL: 'Critical', WARNING: 'Warning', OK: 'OK', NO_PLAN: 'No plan', NO_HISTORY: 'No history', INACTIVE: 'Inactive' }

export function MaintenanceSidebar({ query }: { query: string }) {
  const maintenance = useMaintenanceStore(); const scene = useSceneStore(); const map = useMemo(() => getAssetMaintenanceMap(maintenance, scene.objects, maintenance.referenceDate), [maintenance.equipment, maintenance.subassemblies, maintenance.plans, maintenance.events, maintenance.referenceDate, scene.objects]); const kpis = Object.fromEntries(MAINTENANCE_STATUSES.map((status) => [status, [...map.values()].filter((item) => item.status === status).length])) as Record<MaintenanceStatus, number>
  const grouped = useMemo(() => searchGroups(query, maintenance, scene.objects), [query, maintenance.equipment, maintenance.subassemblies, maintenance.events, scene.objects])
  const dueEquipment = useMemo(() => scene.objects.map((asset) => ({ asset, summary: map.get(asset.id) })).filter((item) => item.summary?.nearestDueDate).sort((a, b) => (a.summary?.nearestDueDate ?? '').localeCompare(b.summary?.nearestDueDate ?? '')).slice(0, 12), [scene.objects, map])
  const recentEvents = useMemo(() => { const subassemblyById = new Map(maintenance.subassemblies.map((item) => [item.id, item])); const equipmentById = new Map(maintenance.equipment.map((item) => [item.id, item])); return maintenance.events.slice().sort((a, b) => b.date.localeCompare(a.date)).map((event) => { const subassembly = subassemblyById.get(event.subassemblyId); return { event, subassembly, assetId: equipmentById.get(subassembly?.equipmentId ?? '')?.assetId ?? '' } }).filter((item) => item.assetId).slice(0, 12) }, [maintenance.events, maintenance.subassemblies, maintenance.equipment])
  const chooseAsset = (assetId: string, subassemblyId?: string) => { scene.focusObject(assetId); if (subassemblyId) maintenance.openSubassembly(subassemblyId) }
  const focusResults = () => { const ids = scene.objects.filter((asset) => { const status = map.get(asset.id)?.status; return (maintenance.areaFilter === AREA_FILTER_ALL || asset.areaCode === maintenance.areaFilter) && isLevelVisible(asset.levelCode, maintenance.levelFilter) && (maintenance.statusFilter === 'ALL' || status === maintenance.statusFilter) && (maintenance.criticalityFilter === 'ALL' || asset.criticality === maintenance.criticalityFilter) }).map((asset) => asset.id); if (!ids.length) return; scene.selectOnly(ids[0]); ids.slice(1).forEach(scene.toggleObjectSelection); scene.requestCameraView('fit_selection') }
  const recentCount = (days: number) => { const cutoff = new Date(`${maintenance.referenceDate}T00:00:00Z`); cutoff.setUTCDate(cutoff.getUTCDate() - days); return maintenance.events.filter((event) => new Date(`${event.date}T00:00:00Z`) >= cutoff).length }
  return <aside className="maintenance-sidebar">
    {query ? <section><h3>Resultados</h3>{grouped.equipment.length > 0 && <ResultGroup title="Equipment" items={grouped.equipment.map((item) => ({ id: item.assetId, primary: item.name, secondary: item.id, action: () => chooseAsset(item.assetId) }))} />}{grouped.subassemblies.length > 0 && <ResultGroup title="Subassemblies" items={grouped.subassemblies.map(({ item, assetId }) => ({ id: item.id, primary: item.name, secondary: item.sapId || item.id, action: () => chooseAsset(assetId, item.id) }))} />}{grouped.events.length > 0 && <ResultGroup title="Events" items={grouped.events.map(({ item, assetId }) => ({ id: item.id, primary: item.workOrder || item.type, secondary: item.date, action: () => chooseAsset(assetId, item.subassemblyId) }))} />}{!grouped.equipment.length && !grouped.subassemblies.length && !grouped.events.length && <p className="maintenance-empty">Sin resultados.</p>}</section> : <>
      <section><h3>{maintenance.operationalView === 'DUE' ? 'Vencimientos' : maintenance.operationalView === 'RECENT' ? 'Cambios recientes' : 'Overview'}</h3>{maintenance.operationalView === 'STATUS' ? <div className="maintenance-overview-list">{MAINTENANCE_STATUSES.filter((status) => status !== 'INACTIVE').map((status) => <button key={status} className={maintenance.statusFilter === status ? 'active' : ''} onClick={() => { maintenance.setStatusFilter(maintenance.statusFilter === status ? 'ALL' : status); maintenance.setRecentDays(null) }}><span className={`status-dot status-${status}`} />{labels[status]}<strong>{kpis[status]}</strong></button>)}</div> : maintenance.operationalView === 'DUE' ? <div className="maintenance-result-group">{dueEquipment.map(({ asset, summary }) => <button key={asset.id} onClick={() => chooseAsset(asset.id)}><strong>{asset.name}</strong><small>{summary?.nearestDueDate} · {summary?.status}</small></button>)}{!dueEquipment.length && <p className="maintenance-empty">No hay vencimientos calculados.</p>}</div> : <div className="maintenance-result-group">{recentEvents.map(({ event, subassembly, assetId }) => <button key={event.id} onClick={() => chooseAsset(assetId, event.subassemblyId)}><strong>{event.type} · {subassembly?.name}</strong><small>{event.date}{event.workOrder ? ` · OT ${event.workOrder}` : ''}</small></button>)}{!recentEvents.length && <p className="maintenance-empty">No hay cambios recientes.</p>}</div>}</section>
      <section><h3>Filters</h3><label>Area<select value={maintenance.areaFilter} onChange={(event) => maintenance.setAreaFilter(event.target.value as typeof maintenance.areaFilter)}><option value={AREA_FILTER_ALL}>Todas las areas</option>{PLANT_AREAS.map((area) => <option key={area.code} value={area.code}>{areaLabel(area.code)}</option>)}</select></label><label>Nivel<select value={maintenance.levelFilter} onChange={(event) => maintenance.setLevelFilter(event.target.value as typeof maintenance.levelFilter)}><option value={ALL_LEVELS}>Todos</option><option value={LEVEL_0}>Nivel 0</option><option value={LEVEL_1}>Nivel 1</option></select></label><label>Estado<select value={maintenance.statusFilter} onChange={(event) => maintenance.setStatusFilter(event.target.value as typeof maintenance.statusFilter)}><option value="ALL">Todos</option>{MAINTENANCE_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><label>Criticidad<select value={maintenance.criticalityFilter} onChange={(event) => maintenance.setCriticalityFilter(event.target.value as typeof maintenance.criticalityFilter)}><option value="ALL">Todas</option><option>A</option><option>B</option><option>C</option><option>D</option></select></label><div className="maintenance-filter-mode"><button className={maintenance.filterBehavior === 'DIM' ? 'active' : ''} onClick={() => maintenance.setFilterBehavior('DIM')}>Dim</button><button className={maintenance.filterBehavior === 'HIDE' ? 'active' : ''} onClick={() => maintenance.setFilterBehavior('HIDE')}>Hide</button></div><button className="maintenance-focus-results" onClick={focusResults}>Focus Results</button></section>
      <section><h3>Recent</h3>{([7, 30, 90] as const).map((days) => <button className={`maintenance-recent${maintenance.recentDays === days ? ' active' : ''}`} key={days} onClick={() => { maintenance.setRecentDays(maintenance.recentDays === days ? null : days); maintenance.setOperationalView('RECENT') }}><span>Cambios ultimos {days} dias</span><strong>{recentCount(days)}</strong></button>)}</section>
    </>}
  </aside>
}

function ResultGroup({ title, items }: { title: string; items: Array<{ id: string; primary: string; secondary: string; action: () => void }> }) { return <div className="maintenance-result-group"><h4>{title}</h4>{items.slice(0, 12).map((item) => <button key={item.id} onClick={item.action}><strong>{item.primary}</strong><small>{item.secondary}</small></button>)}</div> }
function searchGroups(query: string, data: ReturnType<typeof useMaintenanceStore.getState>, assets: ReturnType<typeof useSceneStore.getState>['objects']) { const q = query.trim().toLowerCase(); if (!q) return { equipment: [], subassemblies: [], events: [] }; const assetMap = new Map(assets.map((asset) => [asset.id, asset])); const linkedAssetIds = new Set(data.equipment.map((item) => item.assetId)); const equipment = [...data.equipment.filter((item) => { const asset = assetMap.get(item.assetId); return [item.id, item.name, item.assetId, asset?.name, asset?.area, asset?.areaCode].some((value) => String(value ?? '').toLowerCase().includes(q)) }), ...assets.filter((asset) => !linkedAssetIds.has(asset.id) && [asset.id, asset.name, asset.area, asset.areaCode].some((value) => String(value ?? '').toLowerCase().includes(q))).map((asset) => ({ id: asset.id, assetId: asset.id, name: asset.name, active: true, source: 'LOCAL' as const, createdAt: '' }))]; const equipmentById = new Map(data.equipment.map((item) => [item.id, item])); const subassemblies = data.subassemblies.filter((item) => [item.id, item.name, item.sapId].some((value) => value.toLowerCase().includes(q))).map((item) => ({ item, assetId: equipmentById.get(item.equipmentId)?.assetId ?? '' })).filter((item) => item.assetId); const subassemblyById = new Map(data.subassemblies.map((item) => [item.id, item])); const events = data.events.filter((item) => [item.id, item.workOrder, item.notes, item.type].some((value) => value.toLowerCase().includes(q))).map((item) => ({ item, assetId: equipmentById.get(subassemblyById.get(item.subassemblyId)?.equipmentId ?? '')?.assetId ?? '' })).filter((item) => item.assetId); return { equipment, subassemblies, events } }
