import { useEffect, useMemo, useState } from 'react'
import { areaLabel } from '../../config/areas'
import { getEquipmentForAsset, getEquipmentSummary, getEventsForSubassembly, getPlanForSubassembly, getSubassembliesForEquipment, getSubassemblyState } from '../../maintenance/domain/maintenanceSelectors'
import { MaintenancePanel } from '../../maintenance/components/MaintenancePanel'
import { useMaintenanceStore } from '../../maintenance/store/maintenanceStore'
import { useSceneStore } from '../../store/sceneStore'
import { navigate } from '../../shared/navigation'

type ContextTab = 'SUMMARY' | 'SUBASSEMBLIES' | 'TIMELINE' | 'PLANS'

export function MaintenanceContextPanel() {
  const maintenance = useMaintenanceStore(); const scene = useSceneStore(); const [tab, setTab] = useState<ContextTab>('SUMMARY'); const asset = scene.objects.find((item) => item.id === scene.selectedObjectId)
  useEffect(() => { setTab('SUMMARY') }, [asset?.id])
  useEffect(() => { if (asset) maintenance.ensureEquipment(asset) }, [asset?.id])
  if (!asset) return <aside className="maintenance-context"><div className="maintenance-context-title"><strong>Maintenance Overview</strong><small>Selecciona un equipo en la planta</small></div><MaintenanceOverviewSummary /></aside>
  const equipment = getEquipmentForAsset(maintenance, asset.id); const subassemblies = equipment ? getSubassembliesForEquipment(maintenance, equipment.id) : []; const summary = equipment ? getEquipmentSummary(maintenance, equipment.id, maintenance.referenceDate) : null
  const allEvents = subassemblies.flatMap((item) => getEventsForSubassembly(maintenance, item.id).map((event) => ({ ...event, subassemblyName: item.name }))).sort((a, b) => b.date.localeCompare(a.date)); const latest = allEvents[0]
  return <aside className="maintenance-context"><div className="maintenance-context-title"><div><small>{asset.id}</small><strong>{asset.name}</strong></div><button onClick={() => navigate(`/editor?asset=${encodeURIComponent(asset.id)}`)}>Open in Plant Editor</button></div><div className="maintenance-context-tabs" role="tablist">{(['SUMMARY', 'SUBASSEMBLIES', 'TIMELINE', 'PLANS'] as const).map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div><div className="maintenance-context-body">
    {tab === 'SUMMARY' && <><div className="maintenance-equipment-meta"><span><small>ID</small>{asset.id}</span><span><small>Area</small>{areaLabel(asset.areaCode)}</span><span><small>Nivel</small>{asset.levelCode}</span><span><small>Criticidad</small>{asset.criticality || '-'}</span></div><div className={`maintenance-equipment-state status-${summary?.status}`}><small>Estado general</small><strong>{summary?.status ?? 'NO_PLAN'}</strong><span>Atencion {summary?.attentionScore ?? 15}/100</span></div><div className="maintenance-summary-grid"><span><strong>{summary?.counts.OVERDUE ?? 0}</strong> vencidos</span><span><strong>{summary?.counts.CRITICAL ?? 0}</strong> criticos</span><span><strong>{summary?.counts.OK ?? 0}</strong> OK</span></div><dl className="maintenance-facts"><dt>Proximo vencimiento</dt><dd>{summary?.nearestDueDate ?? '-'}</dd><dt>Ultimo evento</dt><dd>{latest ? `${latest.date} · ${latest.type} · ${latest.subassemblyName}` : 'Sin historial'}</dd></dl></>}
    {tab === 'SUBASSEMBLIES' && <MaintenancePanel asset={asset} />}
    {tab === 'TIMELINE' && <MaintenancePanel asset={asset} timelineOnly />}
    {tab === 'PLANS' && <div className="maintenance-plans">{subassemblies.map((item) => { const plan = getPlanForSubassembly(maintenance, item.id); const state = getSubassemblyState(maintenance, item.id, maintenance.referenceDate); return <button key={item.id} onClick={() => maintenance.openSubassembly(item.id)}><strong>{item.name}</strong><span>{plan ? `${plan.intervalValue} ${plan.intervalUnit}` : 'Sin plan'}</span><small>Proximo: {state?.nextDueDate ?? '-'}</small></button> })}{!subassemblies.length && <p className="maintenance-empty">Sin planes ni subconjuntos.</p>}</div>}
  </div></aside>
}

function MaintenanceOverviewSummary() { const store = useMaintenanceStore(); const objects = useSceneStore((state) => state.objects); const map = useMemo(() => { const counts = { OVERDUE: 0, CRITICAL: 0, WARNING: 0, OK: 0, NO_PLAN: 0 }; const byArea = new Map<string, number>(); objects.forEach((asset) => { const equipment = getEquipmentForAsset(store, asset.id); const status = equipment ? getEquipmentSummary(store, equipment.id, store.referenceDate).status : 'NO_PLAN'; if (status in counts) counts[status as keyof typeof counts]++; if (status === 'OVERDUE') byArea.set(asset.areaCode, (byArea.get(asset.areaCode) ?? 0) + 1) }); return { counts, byArea } }, [store.equipment, store.subassemblies, store.plans, store.events, store.referenceDate, objects]); return <><div className="maintenance-overview-cards">{Object.entries(map.counts).map(([status, count]) => <button key={status} className={`status-${status}`} onClick={() => store.setStatusFilter(status as typeof store.statusFilter)}><strong>{count}</strong><span>{status}</span></button>)}</div><h3>Overdue por area</h3><div className="maintenance-area-summary">{[...map.byArea.entries()].map(([area, count]) => <button key={area} onClick={() => store.setAreaFilter(area as typeof store.areaFilter)}><span>{areaLabel(area as any)}</span><strong>{count}</strong></button>)}{map.byArea.size === 0 && <p>Sin equipos vencidos.</p>}</div></> }
