import { useState } from 'react'
import { getEventsForSubassembly, getPlanForSubassembly, getSubassemblyState } from '../domain/maintenanceSelectors'
import { useMaintenanceStore } from '../store/maintenanceStore'
import { ExpectedLifeForm } from './ExpectedLifeForm'
import { FunctionalPositionForm } from './ReplacementList'
import { ReplacementEventForm, eventLabels } from './ReplacementEventForm'
import { intervalLabel, replacementStatusLabels, replacementTimingLabel } from './replacementPresentation'

export function ReplacementDetail({ id }: { id: string }) {
  const store = useMaintenanceStore(); const item = store.subassemblies.find((entry) => entry.id === id); const [mode, setMode] = useState<'NONE' | 'EDIT' | 'LIFE' | 'EVENT' | 'REPLACEMENT'>('NONE')
  if (!item) return null
  const plan = getPlanForSubassembly(store, id); const state = getSubassemblyState(store, id, store.referenceDate); const events = getEventsForSubassembly(store, id)
  return <div className="maintenance-drawer"><div className="maintenance-drawer-header"><div><small>{item.sapId || item.id}</small><h3>{item.name}</h3></div><button aria-label="Cerrar" onClick={store.closeDrawer}>×</button></div><div className="maintenance-drawer-body"><span className={`maintenance-chip status-${state?.operationalStatus}`}>{state ? replacementStatusLabels[state.operationalStatus] : 'Sin datos'}</span><strong className="replacement-timing">{replacementTimingLabel(state)}</strong><p>{item.description || 'Sin descripción.'}</p><div className="inspector-actions"><button onClick={() => setMode('REPLACEMENT')}>Registrar recambio</button><button onClick={() => setMode('EVENT')}>Registrar intervención</button><button onClick={() => setMode('LIFE')}>{plan ? 'Editar intervalo' : 'Configurar vida esperada'}</button><button onClick={() => setMode('EDIT')}>Editar posición</button></div><section className="maintenance-plan-card"><strong>{plan?.name ?? 'Sin vida esperada configurada'}</strong>{plan && <><span>Intervalo de recambio: {intervalLabel(plan.intervalValue, plan.intervalUnit)}</span><span>Próximo vencimiento: {state?.nextDueDate ?? '-'}</span></>}</section><h4>Historial</h4>{events.length ? <div className="maintenance-timeline">{events.map((event) => <article key={event.id}><time>{event.date}</time><div><span className="maintenance-chip">{eventLabels[event.type]}</span><strong>{item.name}</strong><p>{event.notes || 'Sin notas'}{event.workOrder ? ` · OT ${event.workOrder}` : ''}</p></div></article>)}</div> : <p className="maintenance-empty">No hay eventos registrados.</p>}</div>{mode === 'EDIT' && <FunctionalPositionForm equipmentId={item.equipmentId} existing={item} onClose={() => setMode('NONE')} />}{mode === 'LIFE' && <ExpectedLifeForm subassemblyId={id} onClose={() => setMode('NONE')} />}{(mode === 'EVENT' || mode === 'REPLACEMENT') && <ReplacementEventForm subassemblyId={id} defaultType={mode === 'REPLACEMENT' ? 'REPLACEMENT' : 'INSPECTION'} onClose={() => setMode('NONE')} />}</div>
}
